webpackJsonp([0xa39b925b3431],{188:function(e,t,r){"use strict";function o(e){return e&&e.__esModule?e:{default:e}}function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function i(e,t){if(!e)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!t||"object"!=typeof t&&"function"!=typeof t?e:t}function u(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Super expression must either be null or a function, not "+typeof t);e.prototype=Object.create(t&&t.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}}),t&&(Object.setPrototypeOf?Object.setPrototypeOf(e,t):e.__proto__=t)}t.__esModule=!0;var a=r(2),s=o(a),c=r(4),f=function(e){function t(){return n(this,t),i(this,e.apply(this,arguments))}return u(t,e),t.prototype.render=function(){return s.default.createElement(c.Progress,{value:33,title:"Failure due to an error",measureLocation:c.ProgressMeasureLocation.outside,variant:c.ProgressVariant.danger})},t}(s.default.Component);f.title="Progress Outside Failure",t.default=f,f.__docgenInfo={description:"",displayName:"ProgressOutsideFailure"},e.exports=t.default}});
//# sourceMappingURL=component---react-core-src-components-progress-examples-progress-outside-failure-js-19063711dd05d6f6ac6e.js.map